package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cabordenventa generated by hbm2java
 */
@Entity
@Table(name = "CABORDENVENTA", schema = "EMPRESA")
public class Cabordenventa implements java.io.Serializable {

	private String opvCodordenprod;
	private Usuarios usuarios;
	private Clientes clientes;
	private BigDecimal opvId;
	private String opvNombrecomplcli;
	private String opvContactocliente;
	private String opvNombrecompldest;
	private String opvTipopago;
	private Character opvEstadoordventa;

	public Cabordenventa() {
	}

	public Cabordenventa(String opvCodordenprod) {
		this.opvCodordenprod = opvCodordenprod;
	}

	public Cabordenventa(String opvCodordenprod, Usuarios usuarios, Clientes clientes, BigDecimal opvId,
			String opvNombrecomplcli, String opvContactocliente, String opvNombrecompldest, String opvTipopago,
			Character opvEstadoordventa) {
		this.opvCodordenprod = opvCodordenprod;
		this.usuarios = usuarios;
		this.clientes = clientes;
		this.opvId = opvId;
		this.opvNombrecomplcli = opvNombrecomplcli;
		this.opvContactocliente = opvContactocliente;
		this.opvNombrecompldest = opvNombrecompldest;
		this.opvTipopago = opvTipopago;
		this.opvEstadoordventa = opvEstadoordventa;
	}

	@Id

	@Column(name = "OPV_CODORDENPROD", unique = true, nullable = false, length = 5)
	public String getOpvCodordenprod() {
		return this.opvCodordenprod;
	}

	public void setOpvCodordenprod(String opvCodordenprod) {
		this.opvCodordenprod = opvCodordenprod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPV_CODUSERVENTA")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPV_CODCLIENTE")
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Column(name = "OPV_ID", precision = 22, scale = 0)
	public BigDecimal getOpvId() {
		return this.opvId;
	}

	public void setOpvId(BigDecimal opvId) {
		this.opvId = opvId;
	}

	@Column(name = "OPV_NOMBRECOMPLCLI")
	public String getOpvNombrecomplcli() {
		return this.opvNombrecomplcli;
	}

	public void setOpvNombrecomplcli(String opvNombrecomplcli) {
		this.opvNombrecomplcli = opvNombrecomplcli;
	}

	@Column(name = "OPV_CONTACTOCLIENTE")
	public String getOpvContactocliente() {
		return this.opvContactocliente;
	}

	public void setOpvContactocliente(String opvContactocliente) {
		this.opvContactocliente = opvContactocliente;
	}

	@Column(name = "OPV_NOMBRECOMPLDEST")
	public String getOpvNombrecompldest() {
		return this.opvNombrecompldest;
	}

	public void setOpvNombrecompldest(String opvNombrecompldest) {
		this.opvNombrecompldest = opvNombrecompldest;
	}

	@Column(name = "OPV_TIPOPAGO")
	public String getOpvTipopago() {
		return this.opvTipopago;
	}

	public void setOpvTipopago(String opvTipopago) {
		this.opvTipopago = opvTipopago;
	}

	@Column(name = "OPV_ESTADOORDVENTA", length = 1)
	public Character getOpvEstadoordventa() {
		return this.opvEstadoordventa;
	}

	public void setOpvEstadoordventa(Character opvEstadoordventa) {
		this.opvEstadoordventa = opvEstadoordventa;
	}

}
