package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cabordencompra generated by hbm2java
 */
@Entity
@Table(name = "CABORDENCOMPRA", schema = "EMPRESA")
public class Cabordencompra implements java.io.Serializable {

	private String opcCodordencompra;
	private Usuarios usuarios;
	private Proveedores proveedores;
	private BigDecimal opcId;
	private String opcRazonsocialprov;
	private String opcContactoprov;
	private String opcFechaorden;
	private String opcTipopago;
	private BigDecimal opcGastocompra;
	private Set<Detordencompra> detordencompras = new HashSet<Detordencompra>(0);

	public Cabordencompra() {
	}

	public Cabordencompra(String opcCodordencompra) {
		this.opcCodordencompra = opcCodordencompra;
	}

	public Cabordencompra(String opcCodordencompra, Usuarios usuarios, Proveedores proveedores, BigDecimal opcId,
			String opcRazonsocialprov, String opcContactoprov, String opcFechaorden, String opcTipopago,
			BigDecimal opcGastocompra, Set<Detordencompra> detordencompras) {
		this.opcCodordencompra = opcCodordencompra;
		this.usuarios = usuarios;
		this.proveedores = proveedores;
		this.opcId = opcId;
		this.opcRazonsocialprov = opcRazonsocialprov;
		this.opcContactoprov = opcContactoprov;
		this.opcFechaorden = opcFechaorden;
		this.opcTipopago = opcTipopago;
		this.opcGastocompra = opcGastocompra;
		this.detordencompras = detordencompras;
	}

	@Id

	@Column(name = "OPC_CODORDENCOMPRA", unique = true, nullable = false, length = 5)
	public String getOpcCodordencompra() {
		return this.opcCodordencompra;
	}

	public void setOpcCodordencompra(String opcCodordencompra) {
		this.opcCodordencompra = opcCodordencompra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPC_CODUSERPRODUCCION")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPC_CODPROV")
	public Proveedores getProveedores() {
		return this.proveedores;
	}

	public void setProveedores(Proveedores proveedores) {
		this.proveedores = proveedores;
	}

	@Column(name = "OPC_ID", precision = 22, scale = 0)
	public BigDecimal getOpcId() {
		return this.opcId;
	}

	public void setOpcId(BigDecimal opcId) {
		this.opcId = opcId;
	}

	@Column(name = "OPC_RAZONSOCIALPROV")
	public String getOpcRazonsocialprov() {
		return this.opcRazonsocialprov;
	}

	public void setOpcRazonsocialprov(String opcRazonsocialprov) {
		this.opcRazonsocialprov = opcRazonsocialprov;
	}

	@Column(name = "OPC_CONTACTOPROV")
	public String getOpcContactoprov() {
		return this.opcContactoprov;
	}

	public void setOpcContactoprov(String opcContactoprov) {
		this.opcContactoprov = opcContactoprov;
	}

	@Column(name = "OPC_FECHAORDEN")
	public String getOpcFechaorden() {
		return this.opcFechaorden;
	}

	public void setOpcFechaorden(String opcFechaorden) {
		this.opcFechaorden = opcFechaorden;
	}

	@Column(name = "OPC_TIPOPAGO")
	public String getOpcTipopago() {
		return this.opcTipopago;
	}

	public void setOpcTipopago(String opcTipopago) {
		this.opcTipopago = opcTipopago;
	}

	@Column(name = "OPC_GASTOCOMPRA", precision = 22, scale = 0)
	public BigDecimal getOpcGastocompra() {
		return this.opcGastocompra;
	}

	public void setOpcGastocompra(BigDecimal opcGastocompra) {
		this.opcGastocompra = opcGastocompra;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cabordencompra")
	public Set<Detordencompra> getDetordencompras() {
		return this.detordencompras;
	}

	public void setDetordencompras(Set<Detordencompra> detordencompras) {
		this.detordencompras = detordencompras;
	}

}
