package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "CLIENTES", schema = "EMPRESA", uniqueConstraints = {
		@UniqueConstraint(columnNames = "RAZONSOCIALCLIENTE"), @UniqueConstraint(columnNames = "CORREOCLIENTE"),
		@UniqueConstraint(columnNames = "TELEFONOCLIENTE"), @UniqueConstraint(columnNames = "RFCCLIENTE") })
public class Clientes implements java.io.Serializable {

	private String codcliente;
	private String idcliente;
	private String nombrecliente;
	private String appatcliente;
	private String apmatcliente;
	private String razonsocialcliente;
	private String rfccliente;
	private String ubigeocliente;
	private String telefonocliente;
	private String correocliente;
	private Set<Cabordenventa> cabordenventas = new HashSet<Cabordenventa>(0);
	private Set<Factura> facturas = new HashSet<Factura>(0);

	public Clientes() {
	}

	public Clientes(String codcliente, String nombrecliente, String appatcliente, String apmatcliente,
			String rfccliente, String ubigeocliente, String telefonocliente, String correocliente) {
		this.codcliente = codcliente;
		this.nombrecliente = nombrecliente;
		this.appatcliente = appatcliente;
		this.apmatcliente = apmatcliente;
		this.rfccliente = rfccliente;
		this.ubigeocliente = ubigeocliente;
		this.telefonocliente = telefonocliente;
		this.correocliente = correocliente;
	}

	public Clientes(String codcliente, String idcliente, String nombrecliente, String appatcliente, String apmatcliente,
			String razonsocialcliente, String rfccliente, String ubigeocliente, String telefonocliente,
			String correocliente, Set<Cabordenventa> cabordenventas, Set<Factura> facturas) {
		this.codcliente = codcliente;
		this.idcliente = idcliente;
		this.nombrecliente = nombrecliente;
		this.appatcliente = appatcliente;
		this.apmatcliente = apmatcliente;
		this.razonsocialcliente = razonsocialcliente;
		this.rfccliente = rfccliente;
		this.ubigeocliente = ubigeocliente;
		this.telefonocliente = telefonocliente;
		this.correocliente = correocliente;
		this.cabordenventas = cabordenventas;
		this.facturas = facturas;
	}

	@Id

	@Column(name = "CODCLIENTE", unique = true, nullable = false, length = 7)
	public String getCodcliente() {
		return this.codcliente;
	}

	public void setCodcliente(String codcliente) {
		this.codcliente = codcliente;
	}

	@Column(name = "IDCLIENTE", length = 5)
	public String getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(String idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "NOMBRECLIENTE", nullable = false, length = 30)
	public String getNombrecliente() {
		return this.nombrecliente;
	}

	public void setNombrecliente(String nombrecliente) {
		this.nombrecliente = nombrecliente;
	}

	@Column(name = "APPATCLIENTE", nullable = false, length = 30)
	public String getAppatcliente() {
		return this.appatcliente;
	}

	public void setAppatcliente(String appatcliente) {
		this.appatcliente = appatcliente;
	}

	@Column(name = "APMATCLIENTE", nullable = false, length = 30)
	public String getApmatcliente() {
		return this.apmatcliente;
	}

	public void setApmatcliente(String apmatcliente) {
		this.apmatcliente = apmatcliente;
	}

	@Column(name = "RAZONSOCIALCLIENTE", unique = true, length = 30)
	public String getRazonsocialcliente() {
		return this.razonsocialcliente;
	}

	public void setRazonsocialcliente(String razonsocialcliente) {
		this.razonsocialcliente = razonsocialcliente;
	}

	@Column(name = "RFCCLIENTE", unique = true, nullable = false, length = 11)
	public String getRfccliente() {
		return this.rfccliente;
	}

	public void setRfccliente(String rfccliente) {
		this.rfccliente = rfccliente;
	}

	@Column(name = "UBIGEOCLIENTE", nullable = false, length = 9)
	public String getUbigeocliente() {
		return this.ubigeocliente;
	}

	public void setUbigeocliente(String ubigeocliente) {
		this.ubigeocliente = ubigeocliente;
	}

	@Column(name = "TELEFONOCLIENTE", unique = true, nullable = false, length = 9)
	public String getTelefonocliente() {
		return this.telefonocliente;
	}

	public void setTelefonocliente(String telefonocliente) {
		this.telefonocliente = telefonocliente;
	}

	@Column(name = "CORREOCLIENTE", unique = true, nullable = false, length = 50)
	public String getCorreocliente() {
		return this.correocliente;
	}

	public void setCorreocliente(String correocliente) {
		this.correocliente = correocliente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<Cabordenventa> getCabordenventas() {
		return this.cabordenventas;
	}

	public void setCabordenventas(Set<Cabordenventa> cabordenventas) {
		this.cabordenventas = cabordenventas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<Factura> facturas) {
		this.facturas = facturas;
	}

}
