package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cotizaciontemp generated by hbm2java
 */
@Entity
@Table(name = "COTIZACIONTEMP", schema = "EMPRESA")
public class Cotizaciontemp implements java.io.Serializable {

	private String coddocumento;
	private String doccliente;
	private BigDecimal totalpagar;
	private Boolean estado;

	public Cotizaciontemp() {
	}

	public Cotizaciontemp(String coddocumento) {
		this.coddocumento = coddocumento;
	}

	public Cotizaciontemp(String coddocumento, String doccliente, BigDecimal totalpagar, Boolean estado) {
		this.coddocumento = coddocumento;
		this.doccliente = doccliente;
		this.totalpagar = totalpagar;
		this.estado = estado;
	}

	@Id

	@Column(name = "CODDOCUMENTO", unique = true, nullable = false)
	public String getCoddocumento() {
		return this.coddocumento;
	}

	public void setCoddocumento(String coddocumento) {
		this.coddocumento = coddocumento;
	}

	@Column(name = "DOCCLIENTE", length = 8)
	public String getDoccliente() {
		return this.doccliente;
	}

	public void setDoccliente(String doccliente) {
		this.doccliente = doccliente;
	}

	@Column(name = "TOTALPAGAR", precision = 22, scale = 0)
	public BigDecimal getTotalpagar() {
		return this.totalpagar;
	}

	public void setTotalpagar(BigDecimal totalpagar) {
		this.totalpagar = totalpagar;
	}

	@Column(name = "ESTADO", precision = 1, scale = 0)
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
