package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cotizaciontempdet generated by hbm2java
 */
@Entity
@Table(name = "COTIZACIONTEMPDET", schema = "EMPRESA")
public class Cotizaciontempdet implements java.io.Serializable {

	private String coddocumento;
	private String codprod;
	private BigDecimal cantidadprod;
	private BigDecimal precioprod;

	public Cotizaciontempdet() {
	}

	public Cotizaciontempdet(String coddocumento) {
		this.coddocumento = coddocumento;
	}

	public Cotizaciontempdet(String coddocumento, String codprod, BigDecimal cantidadprod, BigDecimal precioprod) {
		this.coddocumento = coddocumento;
		this.codprod = codprod;
		this.cantidadprod = cantidadprod;
		this.precioprod = precioprod;
	}

	@Id

	@Column(name = "CODDOCUMENTO", unique = true, nullable = false)
	public String getCoddocumento() {
		return this.coddocumento;
	}

	public void setCoddocumento(String coddocumento) {
		this.coddocumento = coddocumento;
	}

	@Column(name = "CODPROD")
	public String getCodprod() {
		return this.codprod;
	}

	public void setCodprod(String codprod) {
		this.codprod = codprod;
	}

	@Column(name = "CANTIDADPROD", precision = 22, scale = 0)
	public BigDecimal getCantidadprod() {
		return this.cantidadprod;
	}

	public void setCantidadprod(BigDecimal cantidadprod) {
		this.cantidadprod = cantidadprod;
	}

	@Column(name = "PRECIOPROD", precision = 22, scale = 0)
	public BigDecimal getPrecioprod() {
		return this.precioprod;
	}

	public void setPrecioprod(BigDecimal precioprod) {
		this.precioprod = precioprod;
	}

}
