package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detfactura generated by hbm2java
 */
@Entity
@Table(name = "DETFACTURA", schema = "EMPRESA")
public class Detfactura implements java.io.Serializable {

	private BigDecimal idfactura;
	private Productos productos;
	private Factura factura;
	private BigDecimal cantidadproducto;
	private BigDecimal precioproducto;

	public Detfactura() {
	}

	public Detfactura(BigDecimal idfactura, Productos productos, Factura factura) {
		this.idfactura = idfactura;
		this.productos = productos;
		this.factura = factura;
	}

	public Detfactura(BigDecimal idfactura, Productos productos, Factura factura, BigDecimal cantidadproducto,
			BigDecimal precioproducto) {
		this.idfactura = idfactura;
		this.productos = productos;
		this.factura = factura;
		this.cantidadproducto = cantidadproducto;
		this.precioproducto = precioproducto;
	}

	@Id

	@Column(name = "IDFACTURA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdfactura() {
		return this.idfactura;
	}

	public void setIdfactura(BigDecimal idfactura) {
		this.idfactura = idfactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODPRODUCTO", nullable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODFACTURA", nullable = false)
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@Column(name = "CANTIDADPRODUCTO", precision = 22, scale = 0)
	public BigDecimal getCantidadproducto() {
		return this.cantidadproducto;
	}

	public void setCantidadproducto(BigDecimal cantidadproducto) {
		this.cantidadproducto = cantidadproducto;
	}

	@Column(name = "PRECIOPRODUCTO", precision = 22, scale = 0)
	public BigDecimal getPrecioproducto() {
		return this.precioproducto;
	}

	public void setPrecioproducto(BigDecimal precioproducto) {
		this.precioproducto = precioproducto;
	}

}
