package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetordencompraId generated by hbm2java
 */
@Embeddable
public class DetordencompraId implements java.io.Serializable {

	private BigDecimal docIdcompra;
	private String docCodordencompra;
	private String codmateria;
	private BigDecimal cantidad;

	public DetordencompraId() {
	}

	public DetordencompraId(String codmateria) {
		this.codmateria = codmateria;
	}

	public DetordencompraId(BigDecimal docIdcompra, String docCodordencompra, String codmateria, BigDecimal cantidad) {
		this.docIdcompra = docIdcompra;
		this.docCodordencompra = docCodordencompra;
		this.codmateria = codmateria;
		this.cantidad = cantidad;
	}

	@Column(name = "DOC_IDCOMPRA", precision = 22, scale = 0)
	public BigDecimal getDocIdcompra() {
		return this.docIdcompra;
	}

	public void setDocIdcompra(BigDecimal docIdcompra) {
		this.docIdcompra = docIdcompra;
	}

	@Column(name = "DOC_CODORDENCOMPRA", length = 5)
	public String getDocCodordencompra() {
		return this.docCodordencompra;
	}

	public void setDocCodordencompra(String docCodordencompra) {
		this.docCodordencompra = docCodordencompra;
	}

	@Column(name = "CODMATERIA", nullable = false, length = 5)
	public String getCodmateria() {
		return this.codmateria;
	}

	public void setCodmateria(String codmateria) {
		this.codmateria = codmateria;
	}

	@Column(name = "CANTIDAD", precision = 22, scale = 0)
	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetordencompraId))
			return false;
		DetordencompraId castOther = (DetordencompraId) other;

		return ((this.getDocIdcompra() == castOther.getDocIdcompra()) || (this.getDocIdcompra() != null
				&& castOther.getDocIdcompra() != null && this.getDocIdcompra().equals(castOther.getDocIdcompra())))
				&& ((this.getDocCodordencompra() == castOther.getDocCodordencompra())
						|| (this.getDocCodordencompra() != null && castOther.getDocCodordencompra() != null
								&& this.getDocCodordencompra().equals(castOther.getDocCodordencompra())))
				&& ((this.getCodmateria() == castOther.getCodmateria()) || (this.getCodmateria() != null
						&& castOther.getCodmateria() != null && this.getCodmateria().equals(castOther.getCodmateria())))
				&& ((this.getCantidad() == castOther.getCantidad()) || (this.getCantidad() != null
						&& castOther.getCantidad() != null && this.getCantidad().equals(castOther.getCantidad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDocIdcompra() == null ? 0 : this.getDocIdcompra().hashCode());
		result = 37 * result + (getDocCodordencompra() == null ? 0 : this.getDocCodordencompra().hashCode());
		result = 37 * result + (getCodmateria() == null ? 0 : this.getCodmateria().hashCode());
		result = 37 * result + (getCantidad() == null ? 0 : this.getCantidad().hashCode());
		return result;
	}

}
