package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetordenventaId generated by hbm2java
 */
@Embeddable
public class DetordenventaId implements java.io.Serializable {

	private BigDecimal dovId;
	private String dovCodordenventa;
	private String dovCodproducto;
	private String dovFechordenventa;
	private Integer dovUserventa;

	public DetordenventaId() {
	}

	public DetordenventaId(BigDecimal dovId, String dovCodordenventa, String dovCodproducto, String dovFechordenventa,
			Integer dovUserventa) {
		this.dovId = dovId;
		this.dovCodordenventa = dovCodordenventa;
		this.dovCodproducto = dovCodproducto;
		this.dovFechordenventa = dovFechordenventa;
		this.dovUserventa = dovUserventa;
	}

	@Column(name = "DOV_ID", precision = 22, scale = 0)
	public BigDecimal getDovId() {
		return this.dovId;
	}

	public void setDovId(BigDecimal dovId) {
		this.dovId = dovId;
	}

	@Column(name = "DOV_CODORDENVENTA", length = 5)
	public String getDovCodordenventa() {
		return this.dovCodordenventa;
	}

	public void setDovCodordenventa(String dovCodordenventa) {
		this.dovCodordenventa = dovCodordenventa;
	}

	@Column(name = "DOV_CODPRODUCTO", length = 5)
	public String getDovCodproducto() {
		return this.dovCodproducto;
	}

	public void setDovCodproducto(String dovCodproducto) {
		this.dovCodproducto = dovCodproducto;
	}

	@Column(name = "DOV_FECHORDENVENTA")
	public String getDovFechordenventa() {
		return this.dovFechordenventa;
	}

	public void setDovFechordenventa(String dovFechordenventa) {
		this.dovFechordenventa = dovFechordenventa;
	}

	@Column(name = "DOV_USERVENTA", precision = 5, scale = 0)
	public Integer getDovUserventa() {
		return this.dovUserventa;
	}

	public void setDovUserventa(Integer dovUserventa) {
		this.dovUserventa = dovUserventa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetordenventaId))
			return false;
		DetordenventaId castOther = (DetordenventaId) other;

		return ((this.getDovId() == castOther.getDovId()) || (this.getDovId() != null && castOther.getDovId() != null
				&& this.getDovId().equals(castOther.getDovId())))
				&& ((this.getDovCodordenventa() == castOther.getDovCodordenventa())
						|| (this.getDovCodordenventa() != null && castOther.getDovCodordenventa() != null
								&& this.getDovCodordenventa().equals(castOther.getDovCodordenventa())))
				&& ((this.getDovCodproducto() == castOther.getDovCodproducto())
						|| (this.getDovCodproducto() != null && castOther.getDovCodproducto() != null
								&& this.getDovCodproducto().equals(castOther.getDovCodproducto())))
				&& ((this.getDovFechordenventa() == castOther.getDovFechordenventa())
						|| (this.getDovFechordenventa() != null && castOther.getDovFechordenventa() != null
								&& this.getDovFechordenventa().equals(castOther.getDovFechordenventa())))
				&& ((this.getDovUserventa() == castOther.getDovUserventa())
						|| (this.getDovUserventa() != null && castOther.getDovUserventa() != null
								&& this.getDovUserventa().equals(castOther.getDovUserventa())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDovId() == null ? 0 : this.getDovId().hashCode());
		result = 37 * result + (getDovCodordenventa() == null ? 0 : this.getDovCodordenventa().hashCode());
		result = 37 * result + (getDovCodproducto() == null ? 0 : this.getDovCodproducto().hashCode());
		result = 37 * result + (getDovFechordenventa() == null ? 0 : this.getDovFechordenventa().hashCode());
		result = 37 * result + (getDovUserventa() == null ? 0 : this.getDovUserventa().hashCode());
		return result;
	}

}
