package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detordencompra generated by hbm2java
 */
@Entity
@Table(name = "DETORDENCOMPRA", schema = "EMPRESA")
public class Detordencompra implements java.io.Serializable {

	private DetordencompraId id;
	private Materiaprima materiaprima;
	private Cabordencompra cabordencompra;

	public Detordencompra() {
	}

	public Detordencompra(DetordencompraId id, Materiaprima materiaprima) {
		this.id = id;
		this.materiaprima = materiaprima;
	}

	public Detordencompra(DetordencompraId id, Materiaprima materiaprima, Cabordencompra cabordencompra) {
		this.id = id;
		this.materiaprima = materiaprima;
		this.cabordencompra = cabordencompra;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "docIdcompra", column = @Column(name = "DOC_IDCOMPRA", precision = 22, scale = 0)),
			@AttributeOverride(name = "docCodordencompra", column = @Column(name = "DOC_CODORDENCOMPRA", length = 5)),
			@AttributeOverride(name = "codmateria", column = @Column(name = "CODMATERIA", nullable = false, length = 5)),
			@AttributeOverride(name = "cantidad", column = @Column(name = "CANTIDAD", precision = 22, scale = 0)) })
	public DetordencompraId getId() {
		return this.id;
	}

	public void setId(DetordencompraId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODMATERIA", nullable = false, insertable = false, updatable = false)
	public Materiaprima getMateriaprima() {
		return this.materiaprima;
	}

	public void setMateriaprima(Materiaprima materiaprima) {
		this.materiaprima = materiaprima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOC_CODORDENCOMPRA", insertable = false, updatable = false)
	public Cabordencompra getCabordencompra() {
		return this.cabordencompra;
	}

	public void setCabordencompra(Cabordencompra cabordencompra) {
		this.cabordencompra = cabordencompra;
	}

}
