package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "FACTURA", schema = "EMPRESA")
public class Factura implements java.io.Serializable {

	private String codfactura;
	private Clientes clientes;
	private String direccionemision;
	private String direcciondestino;
	private BigDecimal costo;
	private Set<Detfactura> detfacturas = new HashSet<Detfactura>(0);

	public Factura() {
	}

	public Factura(String codfactura) {
		this.codfactura = codfactura;
	}

	public Factura(String codfactura, Clientes clientes, String direccionemision, String direcciondestino,
			BigDecimal costo, Set<Detfactura> detfacturas) {
		this.codfactura = codfactura;
		this.clientes = clientes;
		this.direccionemision = direccionemision;
		this.direcciondestino = direcciondestino;
		this.costo = costo;
		this.detfacturas = detfacturas;
	}

	@Id

	@Column(name = "CODFACTURA", unique = true, nullable = false, length = 7)
	public String getCodfactura() {
		return this.codfactura;
	}

	public void setCodfactura(String codfactura) {
		this.codfactura = codfactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODCLIENTE")
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Column(name = "DIRECCIONEMISION")
	public String getDireccionemision() {
		return this.direccionemision;
	}

	public void setDireccionemision(String direccionemision) {
		this.direccionemision = direccionemision;
	}

	@Column(name = "DIRECCIONDESTINO")
	public String getDirecciondestino() {
		return this.direcciondestino;
	}

	public void setDirecciondestino(String direcciondestino) {
		this.direcciondestino = direcciondestino;
	}

	@Column(name = "COSTO", precision = 12)
	public BigDecimal getCosto() {
		return this.costo;
	}

	public void setCosto(BigDecimal costo) {
		this.costo = costo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "factura")
	public Set<Detfactura> getDetfacturas() {
		return this.detfacturas;
	}

	public void setDetfacturas(Set<Detfactura> detfacturas) {
		this.detfacturas = detfacturas;
	}

}
