package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name = "INVENTARIO", schema = "EMPRESA")
public class Inventario implements java.io.Serializable {

	private String codinventario;
	private BigDecimal idinventario;
	private BigDecimal cantidadproductoinicial;
	private BigDecimal cantidadproductofinal;
	private BigDecimal precioventaprod;
	private BigDecimal cantvendprod;
	private BigDecimal gananciaProducto;
	private Set<Productos> productoses = new HashSet<Productos>(0);

	public Inventario() {
	}

	public Inventario(String codinventario, BigDecimal cantidadproductoinicial, BigDecimal cantidadproductofinal,
			BigDecimal precioventaprod) {
		this.codinventario = codinventario;
		this.cantidadproductoinicial = cantidadproductoinicial;
		this.cantidadproductofinal = cantidadproductofinal;
		this.precioventaprod = precioventaprod;
	}

	public Inventario(String codinventario, BigDecimal idinventario, BigDecimal cantidadproductoinicial,
			BigDecimal cantidadproductofinal, BigDecimal precioventaprod, BigDecimal cantvendprod,
			BigDecimal gananciaProducto, Set<Productos> productoses) {
		this.codinventario = codinventario;
		this.idinventario = idinventario;
		this.cantidadproductoinicial = cantidadproductoinicial;
		this.cantidadproductofinal = cantidadproductofinal;
		this.precioventaprod = precioventaprod;
		this.cantvendprod = cantvendprod;
		this.gananciaProducto = gananciaProducto;
		this.productoses = productoses;
	}

	@Id

	@Column(name = "CODINVENTARIO", unique = true, nullable = false, length = 5)
	public String getCodinventario() {
		return this.codinventario;
	}

	public void setCodinventario(String codinventario) {
		this.codinventario = codinventario;
	}

	@Column(name = "IDINVENTARIO", precision = 22, scale = 0)
	public BigDecimal getIdinventario() {
		return this.idinventario;
	}

	public void setIdinventario(BigDecimal idinventario) {
		this.idinventario = idinventario;
	}

	@Column(name = "CANTIDADPRODUCTOINICIAL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCantidadproductoinicial() {
		return this.cantidadproductoinicial;
	}

	public void setCantidadproductoinicial(BigDecimal cantidadproductoinicial) {
		this.cantidadproductoinicial = cantidadproductoinicial;
	}

	@Column(name = "CANTIDADPRODUCTOFINAL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCantidadproductofinal() {
		return this.cantidadproductofinal;
	}

	public void setCantidadproductofinal(BigDecimal cantidadproductofinal) {
		this.cantidadproductofinal = cantidadproductofinal;
	}

	@Column(name = "PRECIOVENTAPROD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPrecioventaprod() {
		return this.precioventaprod;
	}

	public void setPrecioventaprod(BigDecimal precioventaprod) {
		this.precioventaprod = precioventaprod;
	}

	@Column(name = "CANTVENDPROD", precision = 22, scale = 0)
	public BigDecimal getCantvendprod() {
		return this.cantvendprod;
	}

	public void setCantvendprod(BigDecimal cantvendprod) {
		this.cantvendprod = cantvendprod;
	}

	@Column(name = "GANANCIA_PRODUCTO", precision = 22, scale = 0)
	public BigDecimal getGananciaProducto() {
		return this.gananciaProducto;
	}

	public void setGananciaProducto(BigDecimal gananciaProducto) {
		this.gananciaProducto = gananciaProducto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inventario")
	public Set<Productos> getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set<Productos> productoses) {
		this.productoses = productoses;
	}

}
