package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Materiaprima generated by hbm2java
 */
@Entity
@Table(name = "MATERIAPRIMA", schema = "EMPRESA", uniqueConstraints = @UniqueConstraint(columnNames = "NOMBREMATPRIMA"))
public class Materiaprima implements java.io.Serializable {

	private String codmatprima;
	private BigDecimal idmatprima;
	private String nombrematprima;
	private BigDecimal preciomatprima;
	private BigDecimal cantidadmatprima;
	private String fechaprodMatprima;
	private String descripcion;
	private BigDecimal gastomatprima;
	private Set<Detordencompra> detordencompras = new HashSet<Detordencompra>(0);

	public Materiaprima() {
	}

	public Materiaprima(String codmatprima, String nombrematprima, BigDecimal preciomatprima,
			BigDecimal cantidadmatprima) {
		this.codmatprima = codmatprima;
		this.nombrematprima = nombrematprima;
		this.preciomatprima = preciomatprima;
		this.cantidadmatprima = cantidadmatprima;
	}

	public Materiaprima(String codmatprima, BigDecimal idmatprima, String nombrematprima, BigDecimal preciomatprima,
			BigDecimal cantidadmatprima, String fechaprodMatprima, String descripcion, BigDecimal gastomatprima,
			Set<Detordencompra> detordencompras) {
		this.codmatprima = codmatprima;
		this.idmatprima = idmatprima;
		this.nombrematprima = nombrematprima;
		this.preciomatprima = preciomatprima;
		this.cantidadmatprima = cantidadmatprima;
		this.fechaprodMatprima = fechaprodMatprima;
		this.descripcion = descripcion;
		this.gastomatprima = gastomatprima;
		this.detordencompras = detordencompras;
	}

	@Id

	@Column(name = "CODMATPRIMA", unique = true, nullable = false, length = 5)
	public String getCodmatprima() {
		return this.codmatprima;
	}

	public void setCodmatprima(String codmatprima) {
		this.codmatprima = codmatprima;
	}

	@Column(name = "IDMATPRIMA", precision = 22, scale = 0)
	public BigDecimal getIdmatprima() {
		return this.idmatprima;
	}

	public void setIdmatprima(BigDecimal idmatprima) {
		this.idmatprima = idmatprima;
	}

	@Column(name = "NOMBREMATPRIMA", unique = true, nullable = false, length = 50)
	public String getNombrematprima() {
		return this.nombrematprima;
	}

	public void setNombrematprima(String nombrematprima) {
		this.nombrematprima = nombrematprima;
	}

	@Column(name = "PRECIOMATPRIMA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPreciomatprima() {
		return this.preciomatprima;
	}

	public void setPreciomatprima(BigDecimal preciomatprima) {
		this.preciomatprima = preciomatprima;
	}

	@Column(name = "CANTIDADMATPRIMA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCantidadmatprima() {
		return this.cantidadmatprima;
	}

	public void setCantidadmatprima(BigDecimal cantidadmatprima) {
		this.cantidadmatprima = cantidadmatprima;
	}

	@Column(name = "FECHAPROD_MATPRIMA", length = 15)
	public String getFechaprodMatprima() {
		return this.fechaprodMatprima;
	}

	public void setFechaprodMatprima(String fechaprodMatprima) {
		this.fechaprodMatprima = fechaprodMatprima;
	}

	@Column(name = "DESCRIPCION", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "GASTOMATPRIMA", precision = 22, scale = 0)
	public BigDecimal getGastomatprima() {
		return this.gastomatprima;
	}

	public void setGastomatprima(BigDecimal gastomatprima) {
		this.gastomatprima = gastomatprima;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiaprima")
	public Set<Detordencompra> getDetordencompras() {
		return this.detordencompras;
	}

	public void setDetordencompras(Set<Detordencompra> detordencompras) {
		this.detordencompras = detordencompras;
	}

}
