package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTOS", schema = "EMPRESA", uniqueConstraints = @UniqueConstraint(columnNames = "NOMBREPROD"))
public class Productos implements java.io.Serializable {

	private String codprod;
	private Inventario inventario;
	private BigDecimal idprod;
	private String nombreprod;
	private String descripcionprod;
	private BigDecimal precio;
	private Set<Detfactura> detfacturas = new HashSet<Detfactura>(0);
	private Set<Detordenventa> detordenventas = new HashSet<Detordenventa>(0);

	public Productos() {
	}

	public Productos(String codprod, Inventario inventario, String nombreprod) {
		this.codprod = codprod;
		this.inventario = inventario;
		this.nombreprod = nombreprod;
	}

	public Productos(String codprod, Inventario inventario, BigDecimal idprod, String nombreprod,
			String descripcionprod, BigDecimal precio, Set<Detfactura> detfacturas, Set<Detordenventa> detordenventas) {
		this.codprod = codprod;
		this.inventario = inventario;
		this.idprod = idprod;
		this.nombreprod = nombreprod;
		this.descripcionprod = descripcionprod;
		this.precio = precio;
		this.detfacturas = detfacturas;
		this.detordenventas = detordenventas;
	}

	@Id

	@Column(name = "CODPROD", unique = true, nullable = false, length = 5)
	public String getCodprod() {
		return this.codprod;
	}

	public void setCodprod(String codprod) {
		this.codprod = codprod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINVENTORY", nullable = false)
	public Inventario getInventario() {
		return this.inventario;
	}

	public void setInventario(Inventario inventario) {
		this.inventario = inventario;
	}

	@Column(name = "IDPROD", precision = 22, scale = 0)
	public BigDecimal getIdprod() {
		return this.idprod;
	}

	public void setIdprod(BigDecimal idprod) {
		this.idprod = idprod;
	}

	@Column(name = "NOMBREPROD", unique = true, nullable = false, length = 50)
	public String getNombreprod() {
		return this.nombreprod;
	}

	public void setNombreprod(String nombreprod) {
		this.nombreprod = nombreprod;
	}

	@Column(name = "DESCRIPCIONPROD", length = 1000)
	public String getDescripcionprod() {
		return this.descripcionprod;
	}

	public void setDescripcionprod(String descripcionprod) {
		this.descripcionprod = descripcionprod;
	}

	@Column(name = "PRECIO", precision = 22, scale = 0)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set<Detfactura> getDetfacturas() {
		return this.detfacturas;
	}

	public void setDetfacturas(Set<Detfactura> detfacturas) {
		this.detfacturas = detfacturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set<Detordenventa> getDetordenventas() {
		return this.detordenventas;
	}

	public void setDetordenventas(Set<Detordenventa> detordenventas) {
		this.detordenventas = detordenventas;
	}

}
