package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Proveedores generated by hbm2java
 */
@Entity
@Table(name = "PROVEEDORES", schema = "EMPRESA", uniqueConstraints = {
		@UniqueConstraint(columnNames = "RAZON_SOCIAL_PROV"), @UniqueConstraint(columnNames = "CORREOPROV"),
		@UniqueConstraint(columnNames = "RFCPROV"), @UniqueConstraint(columnNames = "TELEFONOPROV") })
public class Proveedores implements java.io.Serializable {

	private String codprov;
	private BigDecimal idprov;
	private String razonSocialProv;
	private String telefonoprov;
	private String rfcprov;
	private String correoprov;
	private String ubigeo;
	private Set<Cabordencompra> cabordencompras = new HashSet<Cabordencompra>(0);

	public Proveedores() {
	}

	public Proveedores(String codprov, BigDecimal idprov, String razonSocialProv, String rfcprov, String ubigeo) {
		this.codprov = codprov;
		this.idprov = idprov;
		this.razonSocialProv = razonSocialProv;
		this.rfcprov = rfcprov;
		this.ubigeo = ubigeo;
	}

	public Proveedores(String codprov, BigDecimal idprov, String razonSocialProv, String telefonoprov, String rfcprov,
			String correoprov, String ubigeo, Set<Cabordencompra> cabordencompras) {
		this.codprov = codprov;
		this.idprov = idprov;
		this.razonSocialProv = razonSocialProv;
		this.telefonoprov = telefonoprov;
		this.rfcprov = rfcprov;
		this.correoprov = correoprov;
		this.ubigeo = ubigeo;
		this.cabordencompras = cabordencompras;
	}

	@Id

	@Column(name = "CODPROV", unique = true, nullable = false, length = 5)
	public String getCodprov() {
		return this.codprov;
	}

	public void setCodprov(String codprov) {
		this.codprov = codprov;
	}

	@Column(name = "IDPROV", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdprov() {
		return this.idprov;
	}

	public void setIdprov(BigDecimal idprov) {
		this.idprov = idprov;
	}

	@Column(name = "RAZON_SOCIAL_PROV", unique = true, nullable = false, length = 50)
	public String getRazonSocialProv() {
		return this.razonSocialProv;
	}

	public void setRazonSocialProv(String razonSocialProv) {
		this.razonSocialProv = razonSocialProv;
	}

	@Column(name = "TELEFONOPROV", unique = true, length = 9)
	public String getTelefonoprov() {
		return this.telefonoprov;
	}

	public void setTelefonoprov(String telefonoprov) {
		this.telefonoprov = telefonoprov;
	}

	@Column(name = "RFCPROV", unique = true, nullable = false, length = 8)
	public String getRfcprov() {
		return this.rfcprov;
	}

	public void setRfcprov(String rfcprov) {
		this.rfcprov = rfcprov;
	}

	@Column(name = "CORREOPROV", unique = true, length = 100)
	public String getCorreoprov() {
		return this.correoprov;
	}

	public void setCorreoprov(String correoprov) {
		this.correoprov = correoprov;
	}

	@Column(name = "UBIGEO", nullable = false, length = 9)
	public String getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(String ubigeo) {
		this.ubigeo = ubigeo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedores")
	public Set<Cabordencompra> getCabordencompras() {
		return this.cabordencompras;
	}

	public void setCabordencompras(Set<Cabordencompra> cabordencompras) {
		this.cabordencompras = cabordencompras;
	}

}
