package com.udemy.backendninja.entity;
// Generated 18-nov-2018 22:05:07 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "USUARIOS", schema = "EMPRESA", uniqueConstraints = { @UniqueConstraint(columnNames = "USERNAME"),
		@UniqueConstraint(columnNames = "TELEFONO"), @UniqueConstraint(columnNames = "EMAILUSUARIO") })
public class Usuarios implements java.io.Serializable {

	private long idusuario;
	private String apellidomaternousuario;
	private String apellidopaternousuario;
	private String contrasena;
	private Long edadusuario;
	private String emailusuario;
	private String nombreusuario;
	private String telefono;
	private String username;
	private Set<Cabordenventa> cabordenventas = new HashSet<Cabordenventa>(0);
	private Set<Detordenventa> detordenventas = new HashSet<Detordenventa>(0);
	private Set<Cabordencompra> cabordencompras = new HashSet<Cabordencompra>(0);

	public Usuarios() {
	}

	public Usuarios(long idusuario, String contrasena, String username) {
		this.idusuario = idusuario;
		this.contrasena = contrasena;
		this.username = username;
	}

	public Usuarios(long idusuario, String apellidomaternousuario, String apellidopaternousuario, String contrasena,
			Long edadusuario, String emailusuario, String nombreusuario, String telefono, String username,
			Set<Cabordenventa> cabordenventas, Set<Detordenventa> detordenventas, Set<Cabordencompra> cabordencompras) {
		this.idusuario = idusuario;
		this.apellidomaternousuario = apellidomaternousuario;
		this.apellidopaternousuario = apellidopaternousuario;
		this.contrasena = contrasena;
		this.edadusuario = edadusuario;
		this.emailusuario = emailusuario;
		this.nombreusuario = nombreusuario;
		this.telefono = telefono;
		this.username = username;
		this.cabordenventas = cabordenventas;
		this.detordenventas = detordenventas;
		this.cabordencompras = cabordencompras;
	}

	@Id

	@Column(name = "IDUSUARIO", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(long idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "APELLIDOMATERNOUSUARIO")
	public String getApellidomaternousuario() {
		return this.apellidomaternousuario;
	}

	public void setApellidomaternousuario(String apellidomaternousuario) {
		this.apellidomaternousuario = apellidomaternousuario;
	}

	@Column(name = "APELLIDOPATERNOUSUARIO")
	public String getApellidopaternousuario() {
		return this.apellidopaternousuario;
	}

	public void setApellidopaternousuario(String apellidopaternousuario) {
		this.apellidopaternousuario = apellidopaternousuario;
	}

	@Column(name = "CONTRASENA", nullable = false, length = 60)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@Column(name = "EDADUSUARIO", precision = 10, scale = 0)
	public Long getEdadusuario() {
		return this.edadusuario;
	}

	public void setEdadusuario(Long edadusuario) {
		this.edadusuario = edadusuario;
	}

	@Column(name = "EMAILUSUARIO", unique = true)
	public String getEmailusuario() {
		return this.emailusuario;
	}

	public void setEmailusuario(String emailusuario) {
		this.emailusuario = emailusuario;
	}

	@Column(name = "NOMBREUSUARIO", length = 50)
	public String getNombreusuario() {
		return this.nombreusuario;
	}

	public void setNombreusuario(String nombreusuario) {
		this.nombreusuario = nombreusuario;
	}

	@Column(name = "TELEFONO", unique = true, length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<Cabordenventa> getCabordenventas() {
		return this.cabordenventas;
	}

	public void setCabordenventas(Set<Cabordenventa> cabordenventas) {
		this.cabordenventas = cabordenventas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<Detordenventa> getDetordenventas() {
		return this.detordenventas;
	}

	public void setDetordenventas(Set<Detordenventa> detordenventas) {
		this.detordenventas = detordenventas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<Cabordencompra> getCabordencompras() {
		return this.cabordencompras;
	}

	public void setCabordencompras(Set<Cabordencompra> cabordencompras) {
		this.cabordencompras = cabordencompras;
	}

}
